export const GET_UPLOADED_STATUS_FAILURE = 'GET_UPLOADED_STATUS_FAILURE';
export const GET_UPLOADED_STATUS_SUCCESS = 'GET_UPLOADED_STATUS_SUCCESS';
export const APPROVED_STATUS_SUCCESS = 'APPROVED_STATUS_SUCCESS';
