export const RECEIVED_ALL_QUESTION_BY_TOPIC  = 'RECEIVED_ALL_QUESTION_BY_TOPIC';
export const FAILED_ALL_QUESTION_BY_TOPIC  = 'FAILED_ALL_QUESTION_BY_TOPIC';
export const RECEIVED_ALL_APPROVED_ITEMS  = 'RECEIVED_ALL_APPROVED_ITEMS';
export const FAILED_ALL_APPROVED_ITEMS  = 'FAILED_ALL_APPROVED_ITEMS';
export const LIKE_COUNT_INCREASE_SUCCESS  = 'LIKE_COUNT_INCREASE_SUCCESS';
export const LIKE_COUNT_INCREASE_FAILED  = 'LIKE_COUNT_INCREASE_FAILED';