export const UPDATE_CART_SAVE_FAILURE = 'UPDATE_CART_SAVE_FAILURE';
export const UPDATE_CART_SAVE_SUCCESS = 'UPDATE_CART_SAVE_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const CLEARED_SESSION_STORAGE = 'CLEARED_SESSION_STORAGE';