export const REVIEW_ITEMS_FAILURE = 'REVIEW_ITEMS_FAILURE';
export const REVIEW_ITEMS_SUCCESS = 'REVIEW_ITEMS_SUCCESS';
export const UPDATE_UPLOAD_STATUS_FAILURE = 'UPDATE_UPLOAD_STATUS_FAILURE';
export const UPDATE_UPLOAD_STATUS_SUCCESS = 'UPDATE_UPLOAD_STATUS_SUCCESS';

    