export const LATEST_SCORE_UPDATED_SUCCESS = 'LATEST_SCORE_UPDATED_SUCCESS'
export const LATEST_SCORE_UPDATED_FAILURE = 'LATEST_SCORE_UPDATED_FAILURE'
export const GET_LEADERBOARD_LIST_FAILURE = 'GET_LEADERBOARD_LIST_FAILURE'
export const GET_LEADERBOARD_LIST_SUCCESS = 'GET_LEADERBOARD_LIST_SUCCESS'